### ISSUE TITLE
Weird Issue: "Read - Out of range! Host notified."

### ISSUE THREAD

**Issue by mayt04** [CTCaer/hekate#1010]
Hello, I have Hekate v6.2.1.
When I use the USB Tools for the emu RAW GPP's and eMMC RAW GPP's BOOT0 and BOOT1 as soon as  I plug the Console to my PC that has  the Windows 11 OS I get this error:
![Hekate_Read_Out_Of_Range](https://github.com/user-attachments/assets/3ba91824-8c1d-4283-a5db-735f3b190c00)

NOTE: I tried with my  Laptop that has Windows 11 and my other PC with Windows 10 and I don't get this error, so other than using those, is there something that I could do to fix this?

**Comment by CTCaer** [comment]
Either the program you used, or your drivers, tried to access out of bounds on boot0.
That's normally a fatal error, but I made it a warning, since I don't allow that to internally reach mmc.
You can ignore it and try to not do read/writes out of bounds.

(I'm leaning towards bad drivers or filter drivers, since you said another pc on same OS doesn't do that.)
