### ISSUE TITLE
[Feature Request] Backup/Restore of individual GPP Partitions

### ISSUE THREAD

**Issue by archit9169** [CTCaer/hekate#1015]
Right now this is partly implemented, that is:

1. We can backup two GPP Partitions - eMMC SYS and eMMC USER.
2. We can restore GPP Partition eMMC ALL which checks for all images to restore instead of any single image.

Proposed Enhancement / Functionality:

1. Individual backup of other partitions as well that make up the raw nand for eMMC.
2. Instead of checking and restoring all eMMC partition, get more control on which partition to restore.
3. Allow similar functionality for emuMMC partitions as well, which is missing at this point.

**Comment by CTCaer** [comment]
You should at least use a feature once before proposing improvements/changes to it.
At minimum read the descriptions I have.

Both your 1 and 2 points, on what it does currently, are incorrect.

1. It does individual backup of all partitions already, since the implementation of it back in 2018. 
   SYS is a moniker for all other 10 partitions. So running both options gives you all 11 partition images.
2. You can already do that by omitting the partition images in the restore folder. It only restores what it finds.
3. I find no reason for that to exist there and complicate the code further, since the most important partition is USER in emuMMC and because of its size, at that point just do the full gpp option.
  You can still ofc restore a partition, just mount the emuMMC partition to your pc and use any of the existing tools for that.

**Comment by archit9169** [comment]
It seems like there might be a miscommunication on my part. 

By individual backup/restore I mean an option where we have control like in TWRP recovery for android. I know that we can simply remove the files if we dont want to restore that partition. That's why I stated Proposed Enhancement / Functionality.

I have used that feature, and thats why I proposed it here. It shows eMMC sys -> which geneartes all partitions except user, and eMMC user -> which only does user. What I propsed was simply giving checkbox type of list for individual partitions for more control.

I understand your point of not adding more changes to avoid complicating the code further, it is after all your own project and you can handle it as per your own wish.

**Comment by CTCaer** [comment]
I find no reason to complicate the code and touch the GUI _mostly_ because you are forced to move a backup into restore folder manually (which is on purpose btw).
So because of that, user can actively decide what to restore by only moving the wanted partitions.
If the backup method was not raw (aka decrypted and file based), then it would make sense to add such support more.
(But even supporting that could actually make the backup even slower if eMMC is not empty.)

**Comment by archit9169** [comment]
Like I said, I understand your point. It was a proposal which does not align with how you want to maintain the code.

Besides, the main functionality is already there. For rest of the stuff, we can do manually using tools like nxnandmanager.
