### ISSUE TITLE
Hekate error: "Missing LP0 (sleep) lib / Missing Minerva lib"

### ISSUE THREAD

**Issue by costantion** [CTCaer/hekate#1020]
Hi everyone,

I'm currently facing an issue with Hekate on my Nintendo Switch. When I try to boot, I get the following error message:

Missing LP0 (sleep) lib!
Missing Minerva lib!
Update bootloader folder!
Press any key...
![hekate](https://github.com/user-attachments/assets/9c8c0013-bafe-4a1d-8e27-83be24fe0f9d)

What I’ve tried so far:
I’ve updated to the latest version of Hekate from the official GitHub page.

Question:
Does anyone have an idea what could be causing this issue? Is there anything I’m missing or something else I should try?

Any help would be greatly appreciated! Thanks in advance!

**Comment by urherenow** [comment]
This isn't a support forum. It told you exactly what you need to do (update your bootloader folder). You must extract THE ENTIRE FOLDER to your card, overwriting all files. If you still get that error, it's still because it can't read those files, meaning your sd card (or reader) is damaged, or not formatted properly. If you've updated to FW 19, you also need to wait until a new version is released, but I don't believe this error has anything to do with that.

**Comment by CTCaer** [comment]
You have a ram issue as it seems. hekate uses ram for various components and if it doesn't work, you can see errors like that.
And I can't do anything on hw issues.
![image](https://github.com/user-attachments/assets/625c64bd-2645-497e-b20b-73d37c4eb124)

**Comment by Link82dsd** [comment]
hello I have exactly the same error could you solve it?

**Comment by Newbit13** [comment]
可能你的sd卡里的bootloader文件夹下有重复命名的文件，删掉其中一个就好。或者重别的地方重新拷贝别人的bootloader文件夹进去覆盖

**Comment by Jimmytheprofessionaldumbass** [comment]
for me it turned out I was formating the wrong way. Im on mac and I did "GUID partition" with MS-DOS (FAT) and that didn't work, but "Master boot record" with MS-DOS (Fat) works. idk whats the name of these formats on windows but theres your first clue. hope this helps
