### ISSUE TITLE
[Enhancement] Better support for custom backgrounds

### ISSUE THREAD

**Issue by Noob0dooN** [CTCaer/hekate#1042]
Currently custom background will only show in the main menu, settings (Not Nyx settings) and if the standard menu isnt "main menu" on that menu but it will revert back to to the base color when exiting and opening. not only whould i like this bug fixed i whould also like having the "toggle background" in "Color themes" to include your custom background when toggling. Also if the background toggle isn't custom background then the main menu whould be a solid color instead of image.

- [ ] Fix custom backgrounds 
- [ ] Add custom background to toggle backgrounds
- [ ] (^Requires) make background solid color if background toggle isn't custom background

**Comment by CTCaer** [comment]
That's not a bug, it's intended that way.
Nyx is software rendered on a GBA-like tiny cpu core. Alpha blending is extremely costly (even on gpus).
And it's way worse on mariko based consoles where ram is clocked at 204mhz.

When home menu is set as launch menu, it's fine the first time because the several seconds waiting is "hidden" by hekate logo.

As for a toggle, there's no point. Just rename background.bmp to background2.bmp or whatever.

Reminder, that most things in Nyx actually had a careful consideration beforehand and deliberate design choices were made.
