### ISSUE TITLE
Can't read/write from/to SD card

### ISSUE THREAD

**Issue by rapsaGnauJ** [CTCaer/hekate#134]
Hekate doesn't backup anything into my SD card. Sometimes it "finishes succesfully" but then there isn't even the backup folder, sometimes it gives me "Error (5) creating file" and sometimes it stops mid-backup. Also can't open /bootloader/hekate_ipl.ini to launch into CFW. The SD card is 128 GB if that matters.

**Comment by CTCaer** [comment]
It seems like your card might be fake.

Can you post a photo of Console info -> Sd card info?

And even better test it with an app like h2testw (after formatting it)

**Comment by rapsaGnauJ** [comment]
Here is the requested picture. I'm passing the test right now, I'll share results in an hour or so. However, I don't think my card is fake because I nearly filled it up sometime. It also works perfectly on PC and Switch. 
![img_20181023_010252](https://user-images.githubusercontent.com/24842781/47324677-22463b80-d661-11e8-8eaf-50f7d5f5372a.jpg)

**Comment by CTCaer** [comment]
Fake always work on writing/reading. But when they fill they just handle garbage data on reads.

It's seems like a genuine Sandisk.
Although, I didn't knew that they still made Class 10 with no U1 or U3.
That's strange.

Normally since many years now, the cards are at least U1. (Don't confuse it with UHS-I. UHS-I is mandatory for U1/U3 rating.)

**Comment by rapsaGnauJ** [comment]
Trying a 4GB class 4 micro SD card. Seems to work ok. The problem must be the card somehow.
