### ISSUE TITLE
Hekate breaks HDCP

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#144]
Hekate breaks HDCP on all modes weather you boot stock or cfw.    weather you use autorcm or a jig.  This issue goes away when using the stock bootloader.    I will quote this here as they have found the issue but it has yet to be fixed in atmo   Hekate has the same issue

https://github.com/Atmosphere-NX/Atmosphere/issues/264

**Comment by CTCaer** [comment]
Did `MC_SECURITY_CARVEOUT2_CLIENT_ACCESS2 = 0x3100000;`
actually fixed it?

**Comment by fennectech** [comment]
It did not.

**Comment by CTCaer** [comment]
Can you try and change this:
https://github.com/CTCaer/hekate/blob/master/bootloader/mem/mc.c#L97

And then stock (through hekate) or without exosphere?

(if you want to try without the mc carveouts you comment this https://github.com/CTCaer/hekate/blob/master/bootloader/main.c#L451 and this https://github.com/CTCaer/hekate/blob/master/bootloader/hos/hos.c#L742)

Also it's better to try with autorcm (and a single press to PWR) and with normal RCM.

**Comment by fennectech** [comment]
Tried the first one before to no success   My jig is broken so no normal RCM.  And ill try the other in about 10 hours when i wake.

**Comment by CTCaer** [comment]
OK. AutoRCM is better because these values are actually set.

A little explanation on commenting these 2 functions:
In 4.0.0+ Ninty started to use secmon to set these. So if commenting them works, it means I'll have to search there.

**Comment by fennectech** [comment]
This ifixes it on stock.   Im now going to try the updated exosphere

**Comment by fennectech** [comment]
any news on this?    i leave tomorrow and wont be able to test for a week

**Comment by CTCaer** [comment]
Not yet. I don't have time currently to make it proper.

**Comment by hexkyz** [comment]
Bringing the necessary changes for fixing the HDCP issue over here:
- Grant TSEC read access to carveout 2 (MC_SECURITY_CARVEOUT2_CLIENT_ACCESS2 = 0x3100000);
- Fix https://github.com/CTCaer/hekate/blob/master/bootloader/mem/mc.c#L134 (CLK_RST_CONTROLLER_RST_DEV_H_SET is now CLK_RST_CONTROLLER_RST_DEV_H_CLR on 4.0.0+);
- Optionally fix https://github.com/CTCaer/hekate/blob/master/bootloader/soc/cluster.c#L129 (CLK_RST_CONTROLLER_RST_CPUG_CMPLX_CLR is now set to 0x41010001 on 5.0.0+);
- Implement carveout configuration on a per-firmware basis.

This issue has been fixed in Atmosphère by removing all carveout configuration from Fusée (which only works due to Exosphère doing it instead), but since Hekate is designed to be a general purpose bootloader, it should be necessary to configure the carveouts differently on each firmware version.

**Comment by CTCaer** [comment]
Ty. I saw your commit also.
That's the plan. To decide later if it should apply them.

I now wonder if the RAM will still be able to retain it's contents after a forced reboot to RCM.
CLK_RST_CONTROLLER_RST_DEV_H_CLR is basically a major bugfix and a big oversight from nintendo.
I normally use that a lot to dump the whole ram after a HOS session.
(I may add a CONFIG_EMC_MC_NO_RESET, depending on the results.)

**Comment by fennectech** [comment]
What about configuring carveouts via a conf file?

**Comment by CTCaer** [comment]
Because there's no need for that bloat. Reading dram after a reboot in rcm, already needs a custom hekate (that dumps it and access the upper ram) and it's only for development purposes.
