### ISSUE TITLE
check the backup directory for backed up files in order to prevent confusion

### ISSUE THREAD

**Issue by akasarx** [CTCaer/hekate#154]
If you backup your NAND, BOOT0, BOOT1, the backed up files will be at /backup/c577483b/ while the restore checks /backup/c577483b/restore/. 

I suggest either checking if the file actually exists, and if not check the directory behind it. Or you can just remove the /restore directory entirely.

 This will prevent confusion such as "Is my NAND/BOOT0/BOOT1 corrupt?" as Error (4) doesn't give you much info.

**Comment by CTCaer** [comment]
That's intended behavior to avoid trigger happy restoring.
I may add a description to Error 4. But that's it.

This would make sense if there was emmc backup manager. But that's not feasible, because of the size of the emmc.

If anyone actually read the path above the bar, would know that it's in the incorrect folder and no confusion would exist..
