### ISSUE TITLE
FatFS Error 13 when using SDSC card

### ISSUE THREAD

**Issue by LetsBladeHD** [CTCaer/hekate#183]
First of all, thank you for all your work. 

My Currently Problem is that i tried to use 3 different SD Cards from different Labels (Sadly all 2gb) and my Switch is telling me that there is a FatFS Error 13 (No FAT found). 

I've tried already 3 different formatters to format them and tried different FAT Modes (FAT(16), FAT32, and exFAT) none of them were working. I've readed about the 1-Pin Issue but i dont know how to find out if its that Problem. 

Currently using: Nintendo Switch Firmware 6.2 with Hekate CTcaer Mod 4.6 and Kosmos 11.9

**Comment by CTCaer** [comment]
Unfortunately the driver does not support SDSC cards.
Only 4GB (SD**HC**) and up are supported.

The reason is the same. 1bit (1-pin) signals are not supported.

You need to upgrade your card, because there's no added support for that in future plans.
(If you want to get the cheapest available, get a 16GB (classs 10 + U1) and not a 4GB. It's 2 vs 3 euro here.)
