### ISSUE TITLE
enhancement : Use custom bootscreen on manual launch.

### ISSUE THREAD

**Issue by GGLinnk** [CTCaer/hekate#24]
Use custom splashscreen on manual launched firmware by user.
For now, when you manually select a firmware there is no bootscreen (But fully works on autoboot).

**Comment by CTCaer** [comment]
This is by design.
The bootlogo at autoboot does 2 jobs.

Waits for user input, so user can enter hekate's menu.
And masks all hekate's magic on firmware launching with a nice logo.

On the other hand, I want the manual launch to display only text, for semi-debugging reasons.
For example when autoboot fails, you can check from manual booting for a possible message.
