### ISSUE TITLE
Unsetting archive bits in large folders slow

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#295]
Unsetting archive bits for large directories (like retroarch's thumbnails / cheats folders results in seconds per file in some files.

**Comment by CTCaer** [comment]
Printing of files doesn't work like that.

It prints files that have the archive bit or folders.

In order to further minimize the stress to BPMP from useless printing, I print ONLY every 10 files fixed.

https://github.com/CTCaer/hekate/blob/master/nyx/nyx_gui/frontend/gui_tools.c#L190

I still update the status bar every 5s. So just let it and forget.

**Comment by fennectech** [comment]
i see   thank you for the clarification
