### ISSUE TITLE
512gb SD Issues

### ISSUE THREAD

**Issue by AntHJ** [CTCaer/hekate#315]
Similar to previous posts I'm getting the error.. failed to init SD..

I've created 3 partitions
16mb .. 480gb SD .. 29gb unpartitioned

Injected 5.0.2 and created an emuMMC
Tried to boot atmosphere and get the error..

**Comment by CTCaer** [comment]
That's the issue.
that 16mb must be just unallocated space.

Basically when you create that huge 480GB partition, you have 3 numbers in the tool:
- unallocated space before (or similar wording)
- partition size
- unallocated space after

So you need to delete all partitions and create the FAT partition and you add 16MiB unallocated space before and 29.16GB (29844MiB or 29856MiB) unallocated space after. You select FAT32 preferably and use 32KB cluster size (or 64KB. Beware though because some tools are bugged and use 16KB instead of 64KB).

After that you create an unformatted or linux **swap** partition in that 29.16GB unallocated space. If you are in linux, then Linux **swap** for emuMMC partition is mandatory.
