### ISSUE TITLE
Suggestion: boot when launch is pressed

### ISSUE THREAD

**Issue by failsafe42** [CTCaer/hekate#342]
I think that if there is only one config option in hekate_ipl.ini, when you press launch it should just boot that option instead of going into the config selection screen.

**Comment by CTCaer** [comment]
Hekate supports auto boot of a boot entry since ever.

Go to options-> auto boot -> select what you want to automatically boot -> hit the save options button on the bottom.
It basically skips the whole procedure of going into the menu.
And you can enter in it again by pressing VOL- when the boot logo is displayed.

You can even change the wait time for bootlogo (it also affects how long it waits for VOL- in case you want to enter the menu again)

**Comment by failsafe42** [comment]
I don't want to completely bypass hekate, I just want the launch button to automatically choose the config.

**Comment by CTCaer** [comment]
Well I don't see a point to that, but anyway, new version will have something else that might work for your use case

**Comment by fennectech** [comment]
I do like the idea of a “boot autoboot” button on the home screen that jsut boots whats currently set as autoboot but the ammount of convience it adds would be minimal.
