### ISSUE TITLE
Wrong version info?

### ISSUE THREAD

**Issue by deurk** [CTCaer/hekate#363]
Updated to latest binary, displays Hekate 5.1.1 but Nyx 0.8.5. Shouldn't it be displaying Hekate 5.1.2?

**Comment by CTCaer** [comment]
Then you didn't. You only updated `bootloader` folder.
Version variable from 5.1.2 released binary:
![image](https://user-images.githubusercontent.com/3665130/76162360-ab222200-6145-11ea-84cf-c42a26e1aed6.png)

Check that your injector pushes `hekate_ctcaer_5.1.2.bin`

Have in mind that the hekate version in Nyx shows the injected binary's version from what I showed above.
And that's why you need to check your injector.

**Comment by deurk** [comment]
My bad, ty.
