### ISSUE TITLE
partition manager d'not detec android

### ISSUE THREAD

**Issue by Kronos2308** [CTCaer/hekate#427]
i you have android flashed 
and try to make emummc 
android is deleted

I should create emunand on the partition that is not android

**Comment by CTCaer** [comment]
Partition manager is destructive. It tells you that multiple times.
The only backup/restore ability it has is to backup up to 1GB of files in the FAT partition.

Also if you used the partition manager, it meant that you didn't have a partition available.

BTW, this behavior will not change, because it complicates the partition manager by a lot.

**Comment by Kronos2308** [comment]
I see 
Ok I didn't know what was intentional
