### ISSUE TITLE
Time config: Add seconds to configure time.

### ISSUE THREAD

**Issue by HXAPEWiZZ** [CTCaer/hekate#509]
please add seconds to the time config when first booting up hekate.

it is hard to set the time accurately to the second when the lowest unit is minutes, and i have to wait until the second overflows to the minute, and that is very boring and it wastes my time, this is especially relevant for those who don't have an easy way to look at seconds.

not relevant:
luckily for me i have already configured a digital clock to display seconds along with minutes and hours.

**Comment by CTCaer** [comment]
Why you even waste time to set correct seconds?
Which is not wasting btw because you are doing it once.

This clock offset only affects hekate and any second accuracy is irrelevant for hekate.
(It only affects time on files which can't be accurate by design and clock display which only shows minutes.)
