### ISSUE TITLE
Black screen after launch cfw-sys

### ISSUE THREAD

**Issue by glosdaz** [CTCaer/hekate#516]
Tryed loads of times with just updating files that was on as card never had issues before doing it that way I've even tryed  redoing SD card from scratch then I don't have any boot options to launch

**Comment by CTCaer** [comment]
Booting 11.0.0 needs the latest atmosphere also.
If updating fails, it's normally a compatibility issue in atmosphere/contents.
Deleting the atmosphere folder can help you remedy that.
Deleting bootloader folder will not help.

If you delete bootloader folder instead of drag n dropping the hekate update, you will lose your boot options.
Reason why I am saying to just drag n drop the updated bootloader folder in sd.
hekate update packages are carefully done in order to not break from other files.
That's why you normally never need to delete the bootloader folder.

You will need to acquire boot options to launch now from where you got them the first time or you can get the template from here: https://github.com/CTCaer/hekate/blob/master/res/hekate_ipl_template.ini 
edit it and remove unneeded entries and then copy it in /bootloader/hekate_ipl.ini.
