### ISSUE TITLE
Light Blue/Cyan screen when I try to boot both cfw or stock from "launch"

### ISSUE THREAD

**Issue by literaleon** [CTCaer/hekate#523]
After updating to 5.5.0, Trying to launch anything grants me the Kosmos logo and then a cyan screen. I am on 11.0.0, if that helps.

**Comment by CTCaer** [comment]
Blue screen is because you are trying to boot cfw that is not compatible with 11.0.0.
You need to update that component also.

And because your atmosphere folder will probably have 11.0.0 incompatible sysmodules, it would be a good idea to start fresh by renaming/deleting the old atmosphere folder and pasting everything from the latest zip.
