### ISSUE TITLE
HOS Support Issue

### ISSUE THREAD

**Issue by Acnh200** [CTCaer/hekate#530]
Hello there, 
I am having issues with the Ini where I cannot seem to locate the newest version of it. When downloading the latest zip for Hekate that folder appears to be empty. Furthermore, I keep getting issues where It says Initializing and then in red letters unknow pacakge1, rsion... failed to launch firmware. Any idea what I am doing wrong? 
Thank you!

**Comment by CTCaer** [comment]
Hi, hekate packages do not ship or overwrite your hekate_ipl.ini.

You need to create it *once* yourself or get one from various guides or packs.
If you want to make it manually, here's a template with many choices to choose:
https://github.com/CTCaer/hekate/blob/master/res/hekate_ipl_template.ini

It's best to not just copy paste it as it is. It's better to keep what you need.

As for the pkg1 unknown version, it's because you inject an older hekate (lower than 5.5.x) that doesn't recognize your installed HOS version (Switch OS).
