### ISSUE TITLE
FatFS Error13

### ISSUE THREAD

**Issue by EauSP** [CTCaer/hekate#562]
I've got an SDXC card with 1TB storage formatted in exFat and when I inject Hekate it shows me this error and doesnt recognize files. I can't format it to Fat32 because it lacks compatibility
![hekate](https://user-images.githubusercontent.com/77455940/104631131-190b7400-569c-11eb-84bf-a93f90b78633.jpeg)
![4](https://user-images.githubusercontent.com/77455940/104631621-cda59580-569c-11eb-9944-1c8f94501919.jpeg)
![f5160d33-31b7-4677-9484-6897191d22c0](https://user-images.githubusercontent.com/77455940/104631625-cf6f5900-569c-11eb-9e72-31bad6339a94.jpeg)
![b9a30118-d100-4658-8c54-3a89aff442da](https://user-images.githubusercontent.com/77455940/104631658-d72efd80-569c-11eb-87a1-0e656823b997.jpeg)

**Comment by CTCaer** [comment]
Your card is fake:
![image](https://user-images.githubusercontent.com/3665130/104632867-fb8fd780-56a6-11eb-8ffe-4b9265ccef78.png)

You can find its real capacity with certain tools and constrain it but it's better to get your money back by returning it.
Because not only it probably has around 16GB capacity but it's also extremely slow (class 4 which means 4MB/s).

Also good thinking in show me the sd card info pic. Helps solving such issues very fast.
