### ISSUE TITLE
emunand not working with 12.0.1

### ISSUE THREAD

**Issue by PASTO666** [CTCaer/hekate#601]
as title says, it stays at nintendo logo when trying to boot with emunand 12.0.1...

**Comment by Whitesttax** [comment]
Can't back up boot0 and boot1 through USB Tools as well. It doesn't show up on My Pc and it freezes after removing USB C cable. Just saying cause on the main page it says it supported 12.0.1.

**Comment by CTCaer** [comment]
@PASTO666 update hekate and atmo
If this still continues you have a sysmodule that is not compatible with the new changes.

@Whitesttax that's irrelevant with HOS version. And also irrelevant with the issue here.
Open a new issue with proper description and experience. And also provide sd card info from console info
