### ISSUE TITLE
Touch issue

### ISSUE THREAD

**Issue by tjinn** [CTCaer/hekate#609]
Touch Panel
Model: Unkown Contact me!
ID: 6D139629
FTB ver: 137C
FW ver: 3B5E
Changes on every boot of Hekate.
Happened a while ago but idk what to do now. 
Calibration just doesn't work.

**Comment by Masamune3210** [comment]
Have you ever had your touch screen replaced? Have you boot into anything other than HOS?

**Comment by tjinn** [comment]
No.
I've only booted into HOS and atmosphere.

**Comment by CTCaer** [comment]
That normally happens if you never booted HOS and your touch chip does not have the nintendo customized configuration and thus missing the command that gets the touch panel model info.
Also make sure that hekate and nyx (bootloader folder files) are the latest.

I would normally suggest you to boot HOS once but you said you already booted, so dunno why it didn't update the touch firmware.

**Comment by tjinn** [comment]
Is it possible to get this information from a nand backup or something?
This happened a while ago but most of the things i was playing didnt use
the feature.

**Comment by tjinn** [comment]
Is there anything I can do to attempt to fix it software wise?

**Comment by CTCaer** [comment]
So basically your touch broke.
If that's the case, you can do nothing in hekate to fix it.
Probably your touch panel or GC module flex cable got unseated?

Anyway that's a hw issue that can't be fixed via software.
