### ISSUE TITLE
Freeze on selecting SD Card USB Mass storage

### ISSUE THREAD

**Issue by corang** [CTCaer/hekate#620]
Hekate freezes upon selecting the sd card UMS tool. I've tried from the partition manager area as well as from the tools area. I have also tried multiple cables and ports on my pc. Hekate is loaded via the guide at switch.homebrew.guide with the fusee-gelee method. SD card is a 256gb Samsung.

**Comment by corang** [comment]
I do get a popup window saying
```
USB Mass Storage
Device: SD Card
Status: Started USB
```

The only thing I'm able to do is hard shutdown the switch

**Comment by CTCaer** [comment]
Edit `bootloader/nyx.ini` and change `bpmpclock=1` to `bpmpclock=2`. (If it was already 2, tell me).
Reply with results.

**Comment by corang** [comment]
> 
> 
> Edit `bootloader/nyx.ini` and change `bpmpclock=1` to `bpmpclock=2`. (If it was already 2, tell me).
> Reply with results.

Same result, did an entire reboot to double check.

**Comment by CTCaer** [comment]
Are you sure it freezes then? What happens in that Started USB screen if you press VOL- and VOL+ or if you remove the cable?

**Comment by corang** [comment]
Pretty sure, dumping a game right now then I'll check, the way the screen is dimmed it looks like it never even finishes the animation of bringing up the popup window.

**Comment by corang** [comment]
Yeah definitely a freeze, no input changes anything except for holding power button. Unplugging the cable and starting it without the cable doesn't do anything different either. I can take a video if that would help?

**Comment by corang** [comment]
The UMS tool in TegraRcmGUI doesn't work either

**Comment by CTCaer** [comment]
If the ums tool in tegrarcmgui (which uses memloader and uboot) doesn't work then you probably have a hardware issue and there's nothing I can do.

**Comment by vos6434** [comment]
It worked on an older version of Hekate but then I updated both cfw and hekate and that's when it also has stopped working for me.

**Comment by olivatooo** [comment]
Same here... idk why it freezes

**Comment by cnelfalk** [comment]
Years later, and I can confirm this also happens to me.

**Comment by swankleey** [comment]
Literally just made an account because I had this same issue (or a very similar issue) and this is how I fixed it. For me, the issue occurred when I went to USB Tools, went to USB Mass Storage, and clicked SD Card. A pop-up would appear, and then the screen would suddenly dim and completely freeze.

The pop-up displayed the following:
```
USB Mass Storage
Device: SD Card
Status: Started UMS
Note: To end it, safely eject from inside the OS.
DO NOT remove the cable!
```

I figured out the reason why it freezes is actually intentional (at least, I think it is). It doesn't want you to close it out unless you go to your file manager, go to your microSD drive (if it is not popping up, make sure you have nothing plugged into your USB-C port on your PC. That was my main issue. It was my MicroSD card reader thingy, but I had taken the MicroSD card out already, so it wasn't actually doing anything. I removed it, and suddenly, the MicroSD drive popped up.), and click the eject button at the top so you eject your MicroSD safely. Once you eject it, your switch should unfreeze and you can click the close button. I don't know if this solution will help everyone, but I couldn't believe after all these years, no one had a solution.

Images provided are of the eject button and the MicroSD card reader thingy that was plugged into my USB-C port that made it so I couldn't see my MicroSD card drive (well, it's not the exact same thing, but it's close enough.)

<img width="698" height="323" alt="Image" src="https://github.com/user-attachments/assets/2b1005f4-b41a-4a27-ad13-47cba8700d2e" />

![Image](https://github.com/user-attachments/assets/60b63a4d-af4e-4564-95a3-50f43ca67754)

Please let me know if this helps!
