### ISSUE TITLE
[Feature request] skip bootlogos

### ISSUE THREAD

**Issue by pixeltester** [CTCaer/hekate#647]
Hello,

I'll just preface this by saying that I know bootlogos can be deactivated but I wanted to ask what you thought about allowing to skip bootlogos by pressing volume plus? Or does this interfere with booting twrp in android for example? If so maybe power could be used?

The use case is for users who like bootlogos but are rebooting frequently to test something, or testing something in atmosphere which is causing a crash and just wanting to get back into atmosphere as quickly as possible without messing around with the bootlogo setting.

**Comment by CTCaer** [comment]
VOL+ will never be used because it interferes with various things.
Twrp is one thing but also it's the button that's used to enter rcm if no autorcm.
If you are going hardcore at testing, you can disable the bootlogo as you said and then enable them again.

That use case is irrelevant imo because you are not doing that all the time.
For that reason I normally reject such requests immediately because of limited binary size.
(it's worth a try asking though because stuff change overtime)
