### ISSUE TITLE
[Feature request] bootwait override per entry

### ISSUE THREAD

**Issue by zemixe** [CTCaer/hekate#654]
Would you consider allowing the bootwait per entry and if it exists it overrides the global setting? The updates to atmosphere got me thinking about this as some users may switch to using fusee.bin to boot atmosphere instead but this could be useful in many cases to allow the user to specify which payloads they want a bootlogo for.

Shortened example:

```
[config]
autoboot=1
bootwait=3

[Atmosphere]
payload=bootloader/payloads/fusee.bin
bootwait=0
icon=bootloader/res/atmosphere.bmp

[L4T Ubuntu Bionic]
payload=switchroot/ubuntu/coreboot.rom
icon=switchroot/ubuntu/icon_ubuntu_hue.bmp
logopath=switchroot/ubuntu/bootlogo_ubuntu.bmp
```

In this example when injecting hekate atmosphere would not have the hekate bootlogo preceeding the atmosphere splash but ubuntu will keep its 3 second bootlogo.

**Comment by CTCaer** [comment]
The bootwait in hekate serves a very specific function.
It's a completely static wait time for user input in order to enter the menu in case of autoboot or wrongly chosen boot entry.

That it has a bootlogo is only a way to remind user that now it's time to press the button. And that user can choose the logo is simply a stylistically choice.

There's no reason to wait on one and not the other.
It's either you want the choice of having time to enter the menu (instead of holding VOL- on injection/boot/reboot/etc) or not.
So if you don't want that, the way to go is bootwait=0.
