### ISSUE TITLE
Hekate 5.6.2 - Can't Boot Into Stock Firmware w/ AutoRCM Enabled

### ISSUE THREAD

**Issue by daylightEX** [CTCaer/hekate#663]
I have updated my bootloader folder and Hekate version to the latest included in release 5.6.2, but now I cannot boot into OFW/stock using the 'Stock' launch option. I can boot into Atmosphere (19.0.5) just fine.

I'm not really sure what to do - when I selected 'Stock' in the launch options with AutoRCM turned on, it just seems to reboot back into RCM mode. The same applies when I selected 'Reboot - OFW' from the Hekate home menu. When AutoRCM is turned off, it works fine.

**Comment by CTCaer** [comment]
That's because you have 13.0.0.
Stock mode needs exosphere from atmosphere and that needs to support the keys of a new version.
The version of atmosphere that has an exosphere that supports 13.0.0 keys is 1.1.0.
And because 0.19.5 is old, you should check on how to update your hekate_ipl.ini for atmosphere 1.0.0 and up. (editing fusee-secondray.bin to package3)
