### ISSUE TITLE
Creating Android partition causes SD UMS incompatibility with Android 11 device

### ISSUE THREAD

**Issue by zemixe** [CTCaer/hekate#689]
I noticed recently that SD UMS was no longer working when connected to my Android 11 device so I tested creating HOS, emuMMC, Linux and Android partitions and I found that the SD can mount with all of them except when an Android partition is created. If an Android partition is present then the device simply wants to format the card: 

![s](https://user-images.githubusercontent.com/88345559/145380974-078d432c-9c77-4234-a7b6-5b7cf34a3839.jpg)

Is it possible to fix that in hekate or is it unavoidable? Thank you.

**Comment by CTCaer** [comment]
That's unavoidable. Android on Switch needs Hybrid MBR - GPT combo.
That's to allow Android and HOS booting.

Ask your phone's vendor to have proper support for Hybrid MBR and not do whatever it does now.
Which is wrong btw, because hybrid mbr if not supported, it should be at least parsed as GPT as per spec.
It basically actively identifies hybrid mbr and rejects the whole storage.

**Comment by zemixe** [comment]
Ah thank you for explaining. Thanks Samsung!

**Comment by Masamune3210** [comment]
Why does it being samsung not surprise me....
