### ISSUE TITLE
help error emummc

### ISSUE THREAD

**Issue by putra1990** [CTCaer/hekate#692]
emummc is forced but not enabled failed to launch hos

**Comment by urherenow** [comment]
Discord or the gbatemp forums are far better places to seek help. Github is for collaborating and submitting bug reports, whereas your issue is 99% likely to be either your fault, or a hardware problem (sd card socket pins, fake sd card, etc...). Nobody can really guess, since you've provided basically no information at all. Make a post at gbatemp, detailing your info (fw version, hekate+Atmosphere versions, Switch model, SD card brand, capacity and what file system it's formatted to, the directory structure on your card, the contents of hekate_ipl.ini, the contents of /emuMMC/, etc...

**Comment by CTCaer** [comment]
you either never created an emummc or you have it disabled as the error says.
