### ISSUE TITLE
error while loading fss0

### ISSUE THREAD

**Issue by ilykami** [CTCaer/hekate#741]
cant load emunand due to 'atmosphere/fusee-secondary.bin wrong ini cfg or missing/corrupt files'

**Comment by urherenow** [comment]
Stop using guides and download the files yourself from the source, and read the manuals while you're at it.

Your Atmosphere files are out of date, as there is no fusee anymore.

**Comment by ilykami** [comment]
All my files are up to date, I reinstalled everything on my sd and it was fine until this morning

**Comment by urherenow** [comment]
Lol... no they aren't. There is NO fusee-primary or fusee-secondary anymore. Only fusee.bin and package3.

**Comment by impeeza** [comment]
Hello, this is no a support site, please go to proper sites like GBATemp or Discord.

Always READ the OP and readme.md before ask for help, if your read IT, you will find what you are using wrong config files.  Since September 6th of 2021, seven months now, the Atmosphere's file fusee-secondary was renamed to package3, so then you did should modify your hekate_ipl.ini file to reflect that change.

if this morning you have a atmosphere less of 1.0.0 and you did update to newer one, you need to edit your hekate_ipl.ini.

**Comment by CTCaer** [comment]
From release that you didn't read:
___
![image](https://user-images.githubusercontent.com/3665130/165197615-a3943ac6-2f80-47d8-8ede-fb512ef9018b.png)
___

And that notice btw, I'm supposed to remove because it's almost a year now.

**Comment by ilykami** [comment]
I know those files done exist, all my files are current and it was all working but after 12 hours it just stopped when I booted from rcm

**Comment by ilykami** [comment]
Oh now it's saying failed to apply nosigchk

**Comment by impeeza** [comment]
Support not here
