### ISSUE TITLE
Hekate makes wrong sized Paritions 

### ISSUE THREAD

**Issue by TriceTheLegend** [CTCaer/hekate#744]
Hey i noticed somethin odd i dont know how to fix it. 
I try to make 3 partitions in Hekate with the newsest version. on my 512gb San disk Ultra its new 
1 for hos 
2 for emummc 29gb 
and 3 for Android with 36gb 

After i click on next step in the Partition manager and the manager is done i go in Windows in the Partition manager and it shows me Wrong sized Partitions.  Normally it would show me 1 partiton with 400gb 1 with 29 and 1 with 36 

but it shows me 2 x 400 gb and 1 time 29gb 
This Problem comes on Three different Switches. With 3 Different SD cards. 

Why is this so ? 

Sometimes the Partitions are Really wrong and i cant install anything. So i have to delete the sd card the SD card Splitting in 30 little pieces i have to mannuly format them get them all together again. This cost my a lot of tiime in the past few days. 
I installed on a few hundred Switches CFW this is new to me 
I know sometimes hekate makes it wrong. 

But on 3 different switches ? with 3 different sd cards ?  What is wrong with Hekate and the Partition manager ? 
this wasnt so on the version before i guess ?  itry use older verisons but the bug comes Again. 
This comes cover and over again whats to do ?

**Comment by CTCaer** [comment]
I'm surprised that you used hekate's partition manager a hundred times and wasted so much time on reformatting only to realize that.

Anyway, here's the gist of it.
That's how Hybrid MBR works when you enable Android. I add FAT and emuMMC partitions in MBR and ofc one more entry for GPT.
The GPT protective partition has the full size of a drive.
That means that Windows where it doesn't support GPT on removable drives, it will show the MBR partitions, which will amount to FAT32 + emuMMC parts + GPT protective, which all of them together are > disk size.

That's purely cosmetic issue that exists in windows though. No partition of these are above disk boundaries.
And btw GPT is needed, because Android is not actually 1 partition. It's 9 partitions and MBR only supports max 4.

That was how it was done, when I added the partition manager, since 2 years now. Nothing changed about that.

Lastly, I would suggest that if you have no clue how partitioning works (and I don't mean seeing fancy blocks in a partition manager), I would suggest to not touch the partitions made by hekate after the fact.
But if you know and want to do touch ups or special changes to GPT, there's a magic button in hekate that fixes what needs to be fixed, that is called Fix Hybrid MBR.
