### ISSUE TITLE
Restore GPT

### ISSUE THREAD

**Issue by lsp199308** [CTCaer/hekate#750]
Hi, is it possible to add repair GPT option in emmc? For some reason screwed up emmc partition and need to restore gpt, thanks

**Comment by CTCaer** [comment]
It is but I probably won't do that because it has various GUID info that changes between emmc and emmc.
For now you can use another tool that can fix that if it exists and supports your emmc size (32GB or 64GB).
Or you can restore the first 34 sectors (17408 bytes) from a raw GPP backup.
You can basically split it and keep that part and then on restoring, when hekate tells you that it's not the proper size, hit PWR to continue.

**Comment by lsp199308** [comment]
thanks
