### ISSUE TITLE
1bit mode sd but no missing/broken pin 

### ISSUE THREAD

**Issue by Yungdaime** [CTCaer/hekate#758]
Hello all I need help, I cant access to my cfw on my switch because 1bit mode.
I buy a new sd card reader and change the old one, but nothing change, after I open my switch because I see some peoples who have broken or missing pin on the motherboard but all seems good on mine.
I test all the pin with a voltmeter but everything look good.
I test the new sd reader on a friend switch and he work good.
My switch seems to read my sd well in ofw but hekate boot in 1bit mode and when I launch fusee I have a fatal error.
I dont try to factory new reset my switch already idk if it can change something.
I test with another clean sd card with only importants files but it's the same.
If somebody have a solution or something your help is welcome, thanks in advance.

**Comment by impeeza** [comment]
Hi, this space is only to report BUGs on Hekate, for support please go to proper channels, like GBATemp and Discord.

Your cause is a Board problem, it's likely you need to replace or the board connector or repair some trace on it,  on GBATemp are a hole thread dedicated to that with instructions and pictures.

**Comment by CTCaer** [comment]
That's a hw issue. Boot via a hekate if that works, otherwise fix your sd card connector.
Something in the motherboard slot or the flex connector is broken or ready to break.
Not a hekate issue either way.
