### ISSUE TITLE
Display panel : contact me !

### ISSUE THREAD

**Issue by Sorries** [CTCaer/hekate#772]
Hello, 

I have recently modded a brand new lite. It says contact the Ctc in the display panel field . How could I do that.

Thanks

**Comment by CTCaer** [comment]
You are already doing that.
So what id it says it has?

**Comment by Sorries** [comment]
It says ID: 40 94 10

**Comment by CTCaer** [comment]
So you have the elusive 0x1040 panel.
Did you see model or vendor or any other markings on the panel and the flex cables?

**Comment by Sorries** [comment]
![IMG_20220817_235109](https://user-images.githubusercontent.com/19967284/185293357-173244d2-647f-4459-b873-f6e953f2efdc.jpg)
![IMG_20220817_235117](https://user-images.githubusercontent.com/19967284/185293362-b08b2f72-155a-4b26-9407-14d4df4b6c94.jpg)
![IMG_20220817_235148](https://user-images.githubusercontent.com/19967284/185293363-56448435-4438-4fbe-acec-ed99eed6a637.jpg)

dram ID 7.00 | 7.00

**Comment by CTCaer** [comment]
Thanks that helps a lot.
I found that panel in a youtube video but was not sure about its model id being 40 94 10.
I will add the info in next release.

Btw the dram id I was talking about is at the left side of the hw info. It's called "DRAM ID" and it's under "SKU".
It's different than the 7.00 one because it comes from fuses and also I have the vendor and model.
Your switch is quite new so telling me what "DRAM ID" you have will help.

It looks like that:
![image](https://user-images.githubusercontent.com/3665130/185365172-92c7ce66-2441-4d4b-87af-c3803bd3602f.png)

**Comment by Sorries** [comment]
No problem

The DRAM ID: 19: Samsung K4U6E3S4AA-MGCL 4GB

**Comment by CTCaer** [comment]
Thanks
