### ISSUE TITLE
Nyx v1.4.0 hangs during eMMC UMS mounting

### ISSUE THREAD

**Issue by dezem** [CTCaer/hekate#787]
With hekate 5.9.0 it's not possible to mount the boot0 / boot1 from eMMC.
If i downgrade to hekate 5.8.0, there are  no problems.

![grafik](https://user-images.githubusercontent.com/11005072/196057762-384e543f-6d00-4925-8354-78dcb15debba.png)

**Comment by CTCaer** [comment]
Confirmed. Btw all eMMC modes are broken. GPP/BOOT0/1. Suprised you reach that far and not hang in `Mounting disk`.
Silly mistake on refactoring:
![image](https://user-images.githubusercontent.com/3665130/196069259-8ef931b9-e8d1-4d17-b729-7acda9846214.png)

For now you can use the 1.3.0 `nyx.bin` (from v5.8.0).
(Changing only Nyx to an older version, does not affect booting HOS 15.0.0 via hekate, aka fss0.)

Thanks for reporting it. Will be fixed in next release.
(If you really need anything from the v1.4.0 Nyx features, tell me and I will compile a binary and attach it here before.)

**Comment by dezem** [comment]
It will be enough in the next release 😉 

Thanks so far!

**Comment by CTCaer** [comment]
Fixed in latest
