### ISSUE TITLE
RCM Loader ONE Plus (White Box) does not inject payload.bin Hekate 6.0.1

### ISSUE THREAD

**Issue by joaomeuputo** [CTCaer/hekate#802]
Hello, after a few tests with my RCMloader ONE Plus (already upgraded firmware version to v2.02), I did notice that Hekate 6.0.1 payload does not work with RCM Loader.

Below are the following Hekate versions and their payload state:
5.6.1 (Pre-installed with RCM Loader) - WORKS
5.9.0 - WORKS
6.0.0 - WORKS
6.0.1 - DOESN'T WORK

NOTE: TegraRCMGui works with 6.0.1 and older versions.

Thanks in advance, and keep doing a great job as usual!

Merry Xmas.

**Comment by urherenow** [comment]
Then use 6.0.0 in your loader. It should not effect anything at all, because if /bootloader/update.bin is a newer version, your switch will use that one anyway. No need to keep updating your RCMloader.

**Comment by CTCaer** [comment]
As I said before that's a bug on rcm loader firmware. You can format the drive to FAT16 with 512B cluster and recopy stuff back.

**Comment by nefariouslegion** [comment]
How do you go about formatting it to FAT16? I seem to only have the option for NTFS or FAT12

**Comment by urherenow** [comment]
https://www.sdcard.org/downloads/formatter/

**Comment by nefariouslegion** [comment]
> https://www.sdcard.org/downloads/formatter/

That still formats it to FAT12 instead of FAT16 as you can see in the screenshot 
![image](https://user-images.githubusercontent.com/89366675/211208215-b0d92981-8391-42a9-b70d-0273c959a014.png)

**Comment by Masamune3210** [comment]
format *: /FS:FAT /Q
where * is the drive letter assigned to the sd card partition

**Comment by nefariouslegion** [comment]
> format *: /FS:FAT /Q where * is the drive letter assigned to the sd card partition

Tried that prior to the rcmloader getting bricked and it just said "Invalid drive specification" even though the drive letter was correct

**Comment by urherenow** [comment]
Because it's a fake, damaged or both, and doesn't even have 1MB capacity. In theory, fat16 should have 4.3MB capacity (4.1MB formatted). My genuine RCMLoader has a 2MB capacity. Yours is only reporting 712kb? I'll just go back to my original reasponse: Keep 6.0.0 on your loader and forget about it. You're not saving any time by updating the loader, because /bootloader/update.bin is still going to be read/checked every time anyway.

**Comment by impeeza** [comment]
please do not use Issue report as support page.  Use Discord or GBATemp for that.

FAT 12 and FAT 16 are used by the formatting utilities indistinctly as the disk is < 2Mb then the utilities always use FAT12

On GBATemp there is a thread about these RCM Gadgets:

https://gbatemp.net/threads/fake-rcmloader-dongles-in-the-wild.620470/post-10024763

please close this issue as is not a Hekate issue.

**Comment by CTCaer** [comment]
@urherenow You basically caused an issue because you are misinformed.
Such devices rely on SFD partition scheme..
That tool is only for normal drives. Not tiny ones.

And FAT12 is also fine. The important thing is the 512 cluster size. The rest are irrelevant.

Anyway, @nefariouslegion you should see if the driver is there and not mounted. If it's not, you should search google on how to make it show up (via fw update or something else).

**Comment by nefariouslegion** [comment]
> @urherenow You basically caused an issue because you are misinformed. Such devices rely on SFD partition scheme.. That tool is only for normal drives. Not tiny ones.
> 
> And FAT12 is also fine. The important thing is the 512 cluster size. The rest are irrelevant.
> 
> Anyway, @nefariouslegion you should see if the driver is there and not mounted. If it's not, you should search google on how to make it show up (via fw update or something else).

I don't think the issue is it not being mounted. It no longer lights up at all whether plugged in or not. So I think the whole thing is bricked. Though oddly it was still fine after running that tool until I removed the loader from the PC. Then it suddenly didn't work.

**Comment by urherenow** [comment]
Sorry. Deleted my other comment to avoid future confusion when others might check for solutions to this problem, but it's showing in OP's reply. But to be fair, I did initially say to leave 6.0.0 on and and to leave it alone. You are the one who suggested trying to format to fat16.

**Comment by CTCaer** [comment]
@nefariouslegion Tell the vendor that you formatted it, via windows format and doesn't work now. Don't tell them exactly how.
And ask them how to show the storage on pc to reformat it with another tool. And tell them that bootloader mode works, since you can fw update.

@urherenow I said to format it. Not partition it, which is what sd formatter does. It uses MBR scheme and also aligns the partition.
These amtel chip's firmware do not support proper partition schemes. They expect SFD.
And as it seems that they don't have a fallback mode into UMS if they fail to read it.

**Comment by urherenow** [comment]
If it’s actually a One Plus, then files are mirrored here for fw upgrade: https://gbatemp.net/download/rcm-loader-one-plus-firmware-v2-02.37758/

**Comment by nefariouslegion** [comment]
The firmware isn’t what I need. I already have that and like I said the RCMLoader is detected in firmware upgrade mode. So I ran the updater hoping it would un-brick it. It ran and said “Pass” but then still remained bricked when not in firmware upgrade mode
________________________________

**Comment by impeeza** [comment]
Seriusly, this is not a suppor site, read the page on gbatemp, you bricked you loader beyond recovery, because you are a Fake one, please close the issue is not related to Hekate.

https://gbatemp.net/threads/fake-rcmloader-dongles-in-the-wild.620470/

**Comment by nefariouslegion** [comment]
Except everything I can find online points to it being real. You’re just assuming it’s fake with almost no evidence. You haven’t even seen it.
________________________________

**Comment by urherenow** [comment]
You couldn’t inject 6.0.1. That’s evidence enough. Want more? You show less than 1MB capacity. It’s a clone.
