### ISSUE TITLE
16.0.0 support

### ISSUE THREAD

**Issue by alemany89** [CTCaer/hekate#825]
Instead of being a issue, i rise this ticket as a doubt, due that atmosphere is working atm on supporting the new ofw 16.0.0 ->

[this](https://github.com/Atmosphere-NX/Atmosphere/pull/2037])

Does Hekate gonna need also a support for this new update?

Thank you in advance!

**Comment by urherenow** [comment]
This is not what github is for. Don’t bother the devs.

 It might need some tweaks, and it might not. It may get a new release simply because of needing to rebuild emummc.kipm with whatever changes sciresm saw the need to make.

otherwise, hekate is a bootloader of sorts. It’s definitely not going to work befor Atmosphere works.
