### ISSUE TITLE
Backup eMMC progress

### ISSUE THREAD

**Issue by manop81** [CTCaer/hekate#844]
I was using the eMMC RAW GPP backup, Hekate 6.0.2.

What does it signify if the backup progress changes color?

Is it normal for it to go backwards? I saw it drop backwards several times as it progressed.

**Comment by CTCaer** [comment]
The white color is the copy process. The green one is the validation of data.
In order to combat fake or broken sd cards, and to make sure that eMMC backup on SD is fine, the data is read back and compared again with eMMC.

On fat32, the bar goes back and forth when that happens.
On exfat, it finishes and then starts from scratch with green-validation bar.

**Comment by manop81** [comment]
Thank you
