### ISSUE TITLE
[Feature request] Allow migrating emuMMC backup folder/files into emuMMC SD file based

### ISSUE THREAD

**Issue by eberhab** [CTCaer/hekate#857]
Hi, I'm on latest hekate v6.0.4, trying to make a backup of emuMMC SD RAW 1 into an SD file. In order achieve this, I am performing the following steps:

- Tools -> Backup eMMC -> With "SD emuMMC RAW Partition" on -> Backup BOOT & GPP
- Home -> emuMMC -> Migrate emuMMC -> "From Backup"

Going this route, however, the "Backup" button in the emuMMC migration tool remains deactivated. Is there any way to debug this/ manually check the prerequisites for this button to become active? Thanks :)

**Comment by CTCaer** [comment]
Since a previous version, emummc is backed up in a different folder than emmc.
So inside /backup/{emmc_serial}/emummc/.

The migration tool expects it in the default directory though. So you need to move them from /backup/{emmc_serial}/emummc/ into /backup/{emmc_serial}/.

I guess I can let it search in emummc folder if emmc one is not found in next version.

**Comment by CTCaer** [comment]
Added in Nyx 1.5.5
