### ISSUE TITLE
Payload Max:  126296 Bytes

### ISSUE THREAD

**Issue by mktm235** [CTCaer/hekate#860]
Can this upper limit be changed?
It seems that this upper limit is set for some reason, but if it cannot be changed, I will give up.

**Comment by CTCaer** [comment]
It's the rcm injection limit imposed via the relocator on the most commonly used injectors.
That bad design is set to stone now. You can't expect thousands of ppl to change how they inject in order to raise that.

Disregarding or removing my warning in hekate's makefile, will not make it magically work there if size is exceeded.
