### ISSUE TITLE
[Feature Request] Ability to set/change "skip autoboot" volume buttons

### ISSUE THREAD

**Issue by vegedb** [CTCaer/hekate#886]
![image](https://github.com/CTCaer/hekate/assets/72070424/f14ce856-5caf-4cd1-b28f-4a49ed2e336c)

As you can see, holding VOL(-) goes to OFW. 

If `autoboot=1` is set, `holding Vol- to skip autoboot` won't work anymore to enter hekate.

Changing it from `Vol-` to `BOTH Vol- TOGETHER with Vol+` combination will solve this issue. 
Hope you could implement this.

**Comment by CTCaer** [comment]
That won't be added for two reasons.
1. hekate uses that combo since 2018 and nothing else used it for something before 2022.
2. It will create quite a confusion the moment a pack or many start using it, since it will invalidate every single guide, help text, etc, and every single expectance from other chainloaded bpmp/ccplex payloads.

Update whatever you are using something better. Especially when it copied hekate's features that are already changed in how they work.

Reminder that anyone that wants a minor personal change, can get the source and recompile with the change needed.
hint:
https://github.com/CTCaer/hekate/blob/e84367e30218e22123cc1612938fd8876f64ee8c/bootloader/main.c#L1021
https://github.com/CTCaer/hekate/blob/e84367e30218e22123cc1612938fd8876f64ee8c/bootloader/gfx/logos.c#L371
https://github.com/CTCaer/hekate/blob/e84367e30218e22123cc1612938fd8876f64ee8c/bootloader/gfx/logos.c#L382
https://github.com/CTCaer/hekate/blob/e84367e30218e22123cc1612938fd8876f64ee8c/bootloader/gfx/logos.c#L408
https://github.com/CTCaer/hekate/blob/e84367e30218e22123cc1612938fd8876f64ee8c/bootloader/gfx/logos.c#L430
