### ISSUE TITLE
[Feature Request] Allowing Keyboard Input In Hekate Recovery Menu

### ISSUE THREAD

**Issue by Jazztache** [CTCaer/hekate#897]
Hello Hekate Team!

I am having an issue where, due to my volume buttons being broken, I cannot navigate the menus correctly nor proceed with installing custom firmware.
If recovery mode supports keyboard input, would it be out of the question to allow USB C keyboard input? This functionality would use the arrow keys, with Enter to confirm.
Thankyou!

**Comment by urherenow** [comment]
Which part of hekate uses volume buttons, exactly? nyx fully utilizes the touch screen, so your question makes little sense. If you're talking about using something like lockpick_rcm, then hekate has nothing to do with whether or not THAT software can use something other than volume buttons. It only launches the payload, then everything is that payload's job.
     On Thursday, October 26, 2023 at 01:12:52 PM GMT+8, Jazztache ***@***.***> wrote:  
 
 


Hello Hekate Team!

I am having an issue where, due to my volume buttons being broken, I cannot navigate the menus correctly nor proceed with installing custom firmware.
If recovery mode supports keyboard input, would it be out of the question to allow USB C keyboard input? This functionality would use the arrow keys, with Enter to confirm.
Thankyou!

**Comment by masagrator** [comment]
Sounds like you didn't install nyx. Install nyx that is included with Hekate already for a long time, and you will be able to use touch screen.

**Comment by Jazztache** [comment]
Ah apologies, seems I mistook Hekate for something else. I was referring to the TUI payload app. 
I might revisit this if I find any issues with Docked mode in Nyx. I think this may be an issue with fusee_gelee, so I'll send this their way instead. 
Thanks for clearing that up.

**Comment by Jazztache** [comment]
Ok, I will check my Nyx installation. I'll have to attempt a re-install, since Hekate isn't detecting Nyx. Didn't realise Nyx was the frontend and should load immediately.
