### ISSUE TITLE
[Feature Request] Add options to prevent accidental disabling of options that could burn fuses

### ISSUE THREAD

**Issue by Sayora77** [CTCaer/hekate#904]
I would appreciate if there were config options that would allow the disabling (either hiding the options or just graying out) of the gui for nogc, autorcm, and emmc restore. Even if this would be too niche/confusing to have a button to enable this in hekate itself, having an ultimate safeguard available in the config would be incredibly desirable for certain use cases.

Example Config Option Names:
`hidenogc=1`
`hideautorcm=1`
`hiderestoreemmc=1`

While obviously this issue can be avoided by simply being careful, it would be extremely helpful for people that would never want to burn any of their fuses under absolutely any circumstances to prevent burning a fuse accidentally. For example:
- Preserving a sys firmware vulnerable to Nereba or Caffeine (Would want restoring emmc disabled to prevent accidentally restoring a backup with a higher firmware, which would then be burned immediately if autorcm was not enabled as a precaution)
- Using cartridges on lower firmware (Would never disable nogc)
- Still holding out hope for some hypothetical future rcmless cold boot exploit that might require an older firmware (Would never disable autorcm)

**Comment by zemixe** [comment]
nogc can be enforced in your atmosphere config with `kip1patch=nogc`

**Comment by urherenow** [comment]
This is the Hekate github.  Atmosphere configs only work when you launch with fusee.

**Comment by zemixe** [comment]
> This is the Hekate github. Atmosphere configs only work when you launch with fusee. Not to mention that nogc is a dumb option at this point.

What? The `kip1patch=` key is specifically to be used when booting with an atmosphere fss0 hekate configuration, it does not work with fusee.

Whether you think it's dumb or not is also irrelevant, if someone wants to use it it's an existing feature and will enforce the nogc patch.

**Comment by urherenow** [comment]
No relevant to this issue one bit, dude. Changing the option in nyx, changes the hekate_ipl file, which is what is used with fss0, not any atmosphere config. This issue is about preventing that option in nyx.

**Comment by zemixe** [comment]
> Not relevant to this issue one bit, dude. Changing the option in nyx, changes the hekate_ipl file, which is what is used with fss0, not any atmosphere config. This issue is about preventing that option in nyx.

Why comment if you have absolutely zero idea what you are talking about? That's your second useless comment.

Anyway it's 100% relevant, it will enforce the nogc for current firmware independent of autonogc being deactivated and furthermore will present an error and stop booting if the patch is not applied or available. So in this user's use case it wouldn't matter if autonogc was accidentally deactivated or turned off since it would be enforced by the boot config.

**Comment by urherenow** [comment]
I do know what I'm talking about. You just caused confusion by saying "nogc can be enforced in your atmosphere config". What you're talking about, is the boot entry/item(s). 

The problem with nogc being that if you upgrade to a firmware that requires another cg fuse to be burnt, but you enable nogc and try booting with a game card in your system, you'll hang on a black screen. Then bug people here or in the forums/discord about it. Been like that since at least fw 10.

**Comment by CTCaer** [comment]
The only valid case here is Nereba or Caffeine, in which case it's on the user and not the scope of hekate's to handhold them.
Especially if unpatched switches.
For all the rest, just burn the fuses already. Anyone that is gonna be in these cases, is a dev and doesn't care about them.
As for gc they can simply patch in the latest fw.
