### ISSUE TITLE
[Enhancement] Fake sdcards alert and data protection measures

### ISSUE THREAD

**Issue by weirdal3333** [CTCaer/hekate#931]
Refuse to do ANY write operations and display a big error screen if the sdcard tests as fake.
Also, perform a test similar to f3probe and validrive the first time hekate is run on a new sdcard.
Fake sdcards are not a rare issue in the community. There is already a function in hekate that detects if a sd is fake or not.

**Comment by CTCaer** [comment]
Using fake sd cards is user's issue.
And it's irrelevant if any write operation happens since it's lost.
The important functions that write (eMMC/emuMMC backup), actually validate the data written.

Having such a test is out of scope, completely.
As you said, you can just check the microsd info for that and if it looks ok you can try to do a full eMMC backup and see if it errors out.
