### ISSUE TITLE
What a MAX ram supported by hekate?

### ISSUE THREAD

**Issue by cystbear** [CTCaer/hekate#932]
Hello guys,

my question is what a MAX ram supported by hekate, at the moment?
8 or 16 gigs?

Also if you can point me to trusted guide about choosing proper RAM chips, whatever of money.
Thanks.

**Comment by CTCaer** [comment]
hekate is irrelevant, since you can patch it. Out of the box and depending on SKU, 3 total ram configs are supported: 4/6/8GB.
As for the soc, it only supports up to 8GB (2 x 4GB x32 modules with 1GB density)

Suggested 4GB modules for 8GB configuration (in performance order):
1. Hynix H9HCNNNCPMMLXR-NEI
2. Hynix H9HCNNNCPMMLXR-NEE
3. Samsung K4UBE3D4AA-MGCR
4. Samsung K4UBE3D4AA-MGCL

More or better ones could exist but these above are tested and solid.
