### ISSUE TITLE
HOS panic occurred!

### ISSUE THREAD

**Issue by OblivionDarkness** [CTCaer/hekate#949]
color: ######, code: 06

have no idea what this error is to do with any help

**Comment by Duffy0079** [comment]
hey  man, just made a github account to reply to this. I literally had the same issue with my switch yesterday after updating the os to version 18.0.0. I'm assuming you did what I did and just went to the nyx git hub page and downloaded the update and tried to copy files. what ended up being the fix for me and my friend was to go to the atmosphere git hub https://github.com/Atmosphere-NX/Atmosphere/releases. download the 1.7.0 pre release and copy/replace those files with the ones on your sd card and your switch should boot into cfw like normal. truly hope this helps

**Comment by josh-vin** [comment]
Wow! @Duffy0079 you are amazing. That is exactly what happened for me. I updated my files to the prerelease ones and its working great again. I thought I bricked it. 

Just for context for anyone else. I also updated to 18.0.0 and updated the firmware with Daybreak and then I rebooted and couldn't get my switch to load again.

Thanks a million for posting here!

**Comment by CTCaer** [comment]
You always need to update both hekate and atmosphere on hos updates.
A blue or yellow screen or error code, basically just tells you that.

**Comment by Lil-Mouse-69** [comment]
> hey man, just made a github account to reply to this. I literally had the same issue with my switch yesterday after updating the os to version 18.0.0. I'm assuming you did what I did and just went to the hekate git hub page and downloaded the update and tried to copy files. what ended up being the fix for me and my friend was to go to the atmosphere git hub https://github.com/Atmosphere-NX/Atmosphere/releases. download the 1.7.0 pre release and copy/replace those files with the ones on your sd card and your switch should boot into cfw like normal. truly hope this helps.

TY so much this fixed my problem in an instant ty
