### ISSUE TITLE
Partition SD Stuck at Analyzing Volumes

### ISSUE THREAD

**Issue by souldbminersmwc** [CTCaer/hekate#981]
V1 Eristsa

**Comment by CTCaer** [comment]
There's no "Analyzing Volumes" things.
If you mean the "Analyzing SD card usage", you should check your sd card for errors.
That part can hang if you have corrupt directories in filesystem, which causes infinite loop.

**Comment by gabrielhalo150-hue** [comment]
I'm having that error too, how did you fix it?

**Comment by CTCaer** [comment]
I already said how, you should check it for errors.
Run chkdsk on it or repartition/reformat it if issue is deeper.

**Comment by gabrielhalo150-hue** [comment]
> I already said how, you should check it for errors. Run chkdsk on it or repartition/reformat it if issue is deeper.

I mean yes, but I have already done this and even though it does not mark any errors, and I formatted it multiple times, when you enter this option it stays here, it does not matter if it is in fat32 in exFat, or if I have formatted it in cluster32 or 64, It doesn't matter how I formatted or repaired it, I couldn't get past here, now, I gave up and simply installed emuMMC on the SD, yes, create partitions and apparently, from what I observed, it was installed on 2 different partitions since |E appears in the atmosphere, so the truth is I no longer knew what I did

**Comment by CTCaer** [comment]
@gabrielhalo150-hue post a photo or screenshot of Console info -> SD Card info

EDIT:
And btw when updating hekate, you are not supposed to delete bootloader folder and lose all configuration.
So if you have an erista and you needed to have bpmpclock > 1, you need to reedit that back.

**Comment by NerdGlaceon** [comment]
Try format the SD card again in fat 32, but using the KDE disk mannager in linux, not windows, linux.
It worked for me.
